### ISSUE TITLE
Visualizations?

### ISSUE THREAD

**Issue by elbamos** [jupyter-scala/jupyter-scala#113]
Is there any support for viewing visualizations from this kernel in jupyter?

**Comment by alexarchambault** [comment]
[plotly-scala](https://github.com/alexarchambault/plotly-scala#from-almond) or [vegas](https://github.com/vegas-viz/Vegas) ought to work with the upcoming version (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
