### ISSUE TITLE
object mllib is not a member of package org.apache.spark

### ISSUE THREAD

**Issue by dthboyd** [jupyter-scala/jupyter-scala#117]
in jupyter notebook i run:
import org.apache.spark.mllib.util.MLUtils
import org.apache.spark.mllib.regression.LabeledPoint
import org.apache.spark.mllib.linalg.Vectors

def toVector( row : Array[String] ) : LabeledPoint = {
    val klass = row(1).charAt(1)-'0'.toDouble-1
    val age = if (row(2).contains("adults")) 1 else 0
    val sex = if (row(3).contains("women")) 1 else 0
    val survived = if (row(4).contains("yes")) 1 else 0
    LabeledPoint(survived, Vectors.dense(klass,age,sex))
}

output

cmd27.sc:1: object mllib is not a member of package org.apache.spark
import org.apache.spark.mllib.util.MLUtils
                        ^cmd27.sc:2: object mllib is not a member of package org.apache.spark
import org.apache.spark.mllib.regression.LabeledPoint
                        ^cmd27.sc:3: object mllib is not a member of package org.apache.spark
import org.apache.spark.mllib.linalg.Vectors
                        ^cmd27.sc:5: not found: type LabeledPoint
def toVector( row : Array[String] ) : LabeledPoint = {
                                      ^cmd27.sc:10: not found: value LabeledPoint
    LabeledPoint(survived, Vectors.dense(klass,age,sex))
    ^cmd27.sc:10: not found: value Vectors
    LabeledPoint(survived, Vectors.dense(klass,age,sex))
                           ^
Compilation Failed

**Comment by sratatata** [comment]
same here, no fix found..

**Comment by Haze211** [comment]
You have missed dependency, this works for me:

import $ivy.`org.apache.spark::spark-mllib:2.0.1`

import org.apache.spark.ml.feature.{ StringIndexer, StringIndexerModel}
import org.apache.spark.ml.feature.VectorAssembler
