### ISSUE TITLE
not found: value display?

### ISSUE THREAD

**Issue by barrymoo** [jupyter-scala/jupyter-scala#170]
Hello All,

I see a few issues which mention `display.html` (most recent: https://github.com/jupyter-scala/jupyter-scala/issues/44#issuecomment-173385480). However, in 0.4.3:

```scala
display.html("Hello World")
```

gives:

```text
cmd24.sc:1: not found: value display
val res24 = display.html("Hello World")
```

Is this a simple fix?

**Comment by mephi42** [comment]
The following worked for me:

`publish.html("some <b>HTML</b>")`

**Comment by barrymoo** [comment]
@mephi42 I don't know how I missed that... Thanks.
