### ISSUE TITLE
how to add a jar?

### ISSUE THREAD

**Issue by ltn614** [jupyter-scala/jupyter-scala#173]
since the 
classpath.addPath("/path/to/file.jar")
gives the error: not found: value classpath
so how can I import a local jar to my notebook?

**Comment by ckchow** [comment]
I think you can publishLocal (or equivalent) and then use a regular ivy import to grab the jar.

**Comment by baram204** [comment]
try this one.

```
import ammonite._, ammonite.ops._
val path = java.nio.file.FileSystems.getDefault().getPath("c:\....\sqlite-jdbc-3.21.0.1.jar")
val x = ammonite.ops.Path(path)
interp.load.cp(x)
```

**Comment by animeshsrivastava24** [comment]
Please close this issue, it's done.

**Comment by erikerlandson** [comment]
I'm using almond-0.1.7 and the above doesn't work for me at all.  `interp.load` doesn't even exist.

![image](https://user-images.githubusercontent.com/259898/45851123-0c55fb80-bcee-11e8-8a5d-55c38063501f.png)
