### ISSUE TITLE
jupyter-scala download error 

### ISSUE THREAD

**Issue by cchang62** [jupyter-scala/jupyter-scala#189]
I am facing the following error while I execute ./jupyter-scala
=================================================
Getting coursier launcher...
Done
Error while downloading https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-RC1/coursier-cli_2.11-1.0.0-RC1-standalone.jar: Connection refused (Connection refused), ignoring it

**Comment by animeshsrivastava24** [comment]
It is working fine for me.

@cchang62

**Comment by cequencer** [comment]
I ran into the exact identical issue and it is because I am running it behind firewall and proxy configuration is needed.  Further information is tracked here:

https://github.com/coursier/coursier/issues/888

**Comment by espears4sq** [comment]
I am experiencing this error as well.
