### ISSUE TITLE
OK to re-run jupyter-scala install?

### ISSUE THREAD

**Issue by CrowDaddy** [jupyter-scala/jupyter-scala#20]
Hi, thanks for all your good work on this - 
I am working with a vagrant-based Jupyter ( from the EdX Spark courses), and want to add Scala so I can use it against my RDDs from that course.
I followed your install instructions for jupyter-scala 2.11 (I realize it should have been 2.10 for Spark), and indeed it shows up as an option in Jupyter, but when I try to execute any Scala code, it just hangs indefinitely with the asterisk inside the square brackets.  I actually installed Scala 2.11 _after_ installing your jupyter-scala, so I am wondering whether I need to re-install so it can find Scala. What do you suggest?  (Scala itself works fine, I confirmed). Thanks!

**Comment by alexarchambault** [comment]
Hi, I don't know much about Vagrant. This looks a bit similar to https://github.com/alexarchambault/jupyter-scala/issues/17, which I wasn't able to reproduce either :-|

Do the log (`/tmp/jupyter-scala.log`) say anything suspicious? Is enough memory available for the kernel? I would have asked for your Java or ipython versions too, but these weren't the problem in https://github.com/alexarchambault/jupyter-scala/issues/17.

**Comment by CrowDaddy** [comment]
Thanks for your reply. 
Is it OK if I try re-running jupyter-scala, so it can find the Scala install? 
I apologize that I am not too expert on Java; is $JAVA_HOME also needed for jupyter-scala? If so, should it point to the location of the java and javac executables? 
Perhaps you have noticed that IBM are now offering free Jupyter access on their datascientistworkbench.com site; perhaps they will want to add Scala to this. 
Best Regards, John 

----- Original Message -----

**Comment by CrowDaddy** [comment]
I just found that IBM's datascientistworkbench.com already supports Scala in the jupyter notebooks; perhaps they are using your code! 


----- Original Message -----

**Comment by mmatloka** [comment]
I also had the problem with not executing code. It appeared on version linked in README on master branch https://oss.sonatype.org/content/repositories/snapshots/com/github/alexarchambault/jupyter/jupyter-scala-cli_2.11.6/0.2.0-SNAPSHOT/jupyter-scala_2.11.6-0.2.0-SNAPSHOT.zip . After that I have tried version from https://github.com/alexarchambault/jupyter-scala/tree/topic/update-readme and it works :)

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one.
