### ISSUE TITLE
ammonite-spark for Spark 1.4.1

### ISSUE THREAD

**Issue by rvernica** [jupyter-scala/jupyter-scala#22]
I am following the Spark setup instructions listed in [Spark.ipynb](https://github.com/alexarchambault/jupyter-scala/blob/topic/spark-example/examples/libraries/Spark.ipynb). I have `Spark 1.4.1`. I have tried using `ammonite-spark_1.3_2.10.5` but it fails when associating with the master.

Is there a version of the package for Spark 1.4.1? I looked in your Sonatype [repository](https://oss.sonatype.org/content/repositories/snapshots/com/github/alexarchambault/) but I could not find it.

Here is what I tried:

```
load.ivy("com.github.alexarchambault" % "ammonite-spark_1.3_2.10.5" % "0.3.1-SNAPSHOT")
// ... and later
Spark.start()
```

Which concluded with:

```
15/08/10 11:41:06 WARN ReliableDeliverySupervisor: Association with remote system [akka.tcp://sparkMaster@master:7077] has failed, address is now gated for [5000] ms. Reason is: [Disassociated].
15/08/10 11:41:26 ERROR SparkDeploySchedulerBackend: Application has been killed. Reason: All masters are unresponsive! Giving up.
```

And in the Spark master log I got:

```
15/08/10 11:41:06 ERROR Remoting: org.apache.spark.deploy.ApplicationDescription; local class incompatible: stream classdesc serialVersionUID = 2596819202403185464, local class serialVersionUID = -7685200927816255400
java.io.InvalidClassException: org.apache.spark.deploy.ApplicationDescription; local class incompatible: stream classdesc serialVersionUID = 2596819202403185464, local class serialVersionUID = -7685200927816255400
```

Thanks!

**Comment by alexarchambault** [comment]
I didn't tried it with spark 1.4 yet, so no artifact for a 1.4 version was published. I'm planning to update jupyter-scala soon, in the coming days / during the month, that's one of the points I wanted to address.

Beware though that the spark module is somewhat experimental. It should work fine with standalone clusters, but not with YARN ones. It's not really "battle-field tested" either (yet), although it has a test suite for standalone clusters which is fine.

**Comment by rvernica** [comment]
Sounds good. I am using a standalone cluster. Looking forward for the updated artifact. BTW, the latest Spark is 1.4.1 (not 1.4), in case it makes a difference when you are building the artifact.

Also, I am not using YARN, but there were some issues with fetching the YARN modules on my side:
```
Spark.start()
:::: WARNINGS
:: problems summary ::
		module not found: org.apache.hadoop#hadoop-yarn-common;1.0.4
	==== local: tried
	  /home/[...]/.ivy2/local/org.apache.hadoop/hadoop-yarn-common/1.0.4/ivys/ivy.xml
	==== public: tried
	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-common/1.0.4/hadoop-yarn-common-1.0.4.pom
	==== sonatype-snapshots: tried
	  https://oss.sonatype.org/content/repositories/snapshots/org/apache/hadoop/hadoop-yarn-common/1.0.4/hadoop-yarn-common-1.0.4.pom
		module not found: org.apache.hadoop#hadoop-yarn-client;1.0.4
```
Maybe it has to do with my proxy. The `load.ivy` command before went through the proxy.

**Comment by mariusvniekerk** [comment]
Plans for 1.5 ?

**Comment by alexarchambault** [comment]
@rvernica @mariusvniekerk Spark 1.4 and 1.5 should now be fine, with e.g.
```scala
load.ivy("com.github.alexarchambault" % "ammonite-spark_1.4_2.10.5" % "0.3.1-SNAPSHOT")
```
or
```scala
load.ivy("com.github.alexarchambault" % "ammonite-spark_1.5_2.10.5" % "0.3.1-SNAPSHOT")
```

I only used them locally for now, although there no reasons it shouldn't be fine on standalone clusters too. Note that there's still non YARN support.

**Comment by DanqingZ** [comment]
@alexarchambault 

I tried to follow your spark.ipynb but got the following errors in the Spark.start()  step

:: problems summary ::
:::: WARNINGS
		module not found: org.apache.hadoop#hadoop-yarn-common;1.0.4

	==== local: tried

	  /Users/danqing0703/.ivy2/local/org.apache.hadoop/hadoop-yarn-common/1.0.4/ivys/ivy.xml

	==== public: tried

	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-common/1.0.4/hadoop-yarn-common-1.0.4.pom

	==== sonatype-snapshots: tried

	  https://oss.sonatype.org/content/repositories/snapshots/org/apache/hadoop/hadoop-yarn-common/1.0.4/hadoop-yarn-common-1.0.4.pom

		module not found: org.apache.hadoop#hadoop-yarn-client;1.0.4

	==== local: tried

	  /Users/danqing0703/.ivy2/local/org.apache.hadoop/hadoop-yarn-client/1.0.4/ivys/ivy.xml

	==== public: tried

	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-client/1.0.4/hadoop-yarn-client-1.0.4.pom

	==== sonatype-snapshots: tried

	  https://oss.sonatype.org/content/repositories/snapshots/org/apache/hadoop/hadoop-yarn-client/1.0.4/hadoop-yarn-client-1.0.4.pom

		module not found: org.apache.hadoop#hadoop-yarn-api;1.0.4

	==== local: tried

	  /Users/danqing0703/.ivy2/local/org.apache.hadoop/hadoop-yarn-api/1.0.4/ivys/ivy.xml

	==== public: tried

	  https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-yarn-api/1.0.4/hadoop-yarn-api-1.0.4.pom

	==== sonatype-snapshots: tried

	  https://oss.sonatype.org/content/repositories/snapshots/org/apache/hadoop/hadoop-yarn-api/1.0.4/hadoop-yarn-api-1.0.4.pom
java.lang.reflect.InvocationTargetException
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	ammonite.interpreter.Interpreter$$anonfun$process$1$$anonfun$apply$21$$anonfun$apply$24$$anonfun$apply$25$$anonfun$11.apply(Interpreter.scala:259)
java.lang.NoClassDefFoundError: Could not initialize class akka.util.Collections$EmptyImmutableSeq$
	akka.japi.Util$.immutableSeq(JavaAPI.scala:229)
	akka.remote.RemoteSettings.<init>(RemoteSettings.scala:30)
	akka.remote.RemoteActorRefProvider.<init>(RemoteActorRefProvider.scala:114)
	sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$2.apply(DynamicAccess.scala:78)
	scala.util.Try$.apply(Try.scala:191)
	akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:73)
	akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	akka.actor.ReflectiveDynamicAccess$$anonfun$createInstanceFor$3.apply(DynamicAccess.scala:84)
	scala.util.Success.flatMap(Try.scala:230)
	akka.actor.ReflectiveDynamicAccess.createInstanceFor(DynamicAccess.scala:84)
	akka.actor.ActorSystemImpl.liftedTree1$1(ActorSystem.scala:584)
	akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:577)
	akka.actor.ActorSystem$.apply(ActorSystem.scala:141)
	akka.actor.ActorSystem$.apply(ActorSystem.scala:118)
	org.apache.spark.util.AkkaUtils$.org$apache$spark$util$AkkaUtils$$doCreateActorSystem(AkkaUtils.scala:122)
	org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:55)
	org.apache.spark.util.AkkaUtils$$anonfun$1.apply(AkkaUtils.scala:54)
	org.apache.spark.util.Utils$$anonfun$startServiceOnPort$1.apply$mcVI$sp(Utils.scala:1837)
	scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:166)
	org.apache.spark.util.Utils$.startServiceOnPort(Utils.scala:1828)
	org.apache.spark.util.AkkaUtils$.createActorSystem(AkkaUtils.scala:57)
	org.apache.spark.SparkEnv$.create(SparkEnv.scala:223)
	org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:163)
	org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:269)
	org.apache.spark.SparkContext.<init>(SparkContext.scala:272)
	ammonite.spark.Spark$SparkContext.<init>(Spark.scala:228)
	ammonite.spark.Spark.sc(Spark.scala:186)
	ammonite.spark.Spark.start(Spark.scala:197)
	cmd9$$user$$anonfun$1.apply$mcV$sp(Main.scala:60)
	cmd9$$user.<init>(Main.scala:61)
	cmd9.<init>(Main.scala:65)
	cmd9$.<init>(Main.scala:39)
	cmd9$.<clinit>(Main.scala)
	cmd9$Main$.$main(Main.scala:34)
	cmd9$Main.$main(Main.scala)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	ammonite.interpreter.Interpreter$$anonfun$process$1$$anonfun$apply$21$$anonfun$apply$24$$anonfun$apply$25$$anonfun$11.apply(Interpreter.scala:259)

**Comment by alexarchambault** [comment]
The [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop), soon to be the default, delegates almost all its spark stuff to [ammonite-spark](https://github.com/alexarchambault/ammonite-spark). Ask there for help once the README of the develop branch gets updated.
