### ISSUE TITLE
inline plot

### ISSUE THREAD

**Issue by adridadou** [jupyter-scala/jupyter-scala#23]
Hi I am new at IPython and Jupyter so it can be that I missed something.

I am very interested at being able to plot graphs based on data generated in Scala.
How can I do that? I can see that in IPython it is doable but cannot find any documentation / example to do it with Scala

Thank you !

**Comment by alexarchambault** [comment]
Hi,

As far as I'm concerned, I only used hand-crafted solutions (like the one illustrated in [this notebook](http://nbviewer.ipython.org/github/alexarchambault/auto-type-class-benchmark/blob/master/Analysis.ipynb), see cells 1, 7, and 8).

I'd love to have things like http://lightning-viz.org/ work here, but I haven't taken the time to investigate yet.

**Comment by cubefriendly** [comment]
That looks pretty cool !!
Great thing with this notebook. I will have a look.
A project that looks a bit like lightning-viz in Scala would be https://github.com/quantifind/wisp

Maybe that can be interesting to integrate it. Thanks for the link it helps a lot

**Comment by cubefriendly** [comment]
Just a question regarding the variable "display" and "load", is I want to integrate it into a lib, is it passed as an implicit val? or do I need to pass it explicitly ?

**Comment by alexarchambault** [comment]
`load` is available implicitly. About `display`, you can instantiate an instance of it yourself, like done [here](https://github.com/alexarchambault/jupyter-scala/blob/3f0652938474d10fccad739c94d5e0c26c6c83d8/api/src/main/scala/jupyter/api/API.scala), and require the implicits that the particular method you want to call on it requires.

To pull their definitions in your project, you can depend on `"com.github.alexarchambault" % "jupyter-scala-api" % "0.1.0-SNAPSHOT" cross CrossVersion.full` (with either scala 2.10.5 or 2.11.6).

Beware that all of this is subject to change, and is not heavily tested as is (although they were precisely made to be used this way).

**Comment by ittayd** [comment]
Note that wisp seems to have most of the required functionality:
```scala
In [5]:
import  com.quantifind.charts.highcharts.SeriesType
val hc = xyToSeries(1 to 10, 1 to 10, SeriesType.line)
Output written to http://TLV-WPVAJ.munich.corp.akamai.com:52412 (CMD + Click link in Mac OSX).
import  com.quantifind.charts.highcharts.SeriesType
hc: com.quantifind.charts.highcharts.Highchart = Highchart(
  List(Series(Vector(Data(1,1,None,None), Data(2,2,None,None), Data(3,3,None,None), Data(4,4,None,None), Data(5,5,None,None), Data(6,6,None,None), Data(7,7,None,None), Data(8,8,None,None), Data(9,9,None,None), Data(10,10,None,None)),None,None,None,Some(line),None,None,None,None,series)),
  Some(Title(,None,None,None,None,None,None,None,title)),
  Some(Chart(Some(xy))),
  None,
  Some(Credits(None,,None,None,)),
  Some(Exporting(chart,None,None,None,None,None,None)),
  None,
  Some(PlotOptions(None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,plotOptions)),
  None,
  true,
  None,
...
In [6]:

hc.toJson
res4: String = """
{"series":[{"data":[{"x":1,"y":1},{"x":2,"y":2},{"x":3,"y":3},{"x":4,"y":4},{"x":5,"y":5},{"x":6,"y":6},{"x":7,"y":7},{"x":8,"y":8},{"x":9,"y":9},{"x":10,"y":10}],"type":"line"}],"exporting":{"filename":"chart"},"yAxis":[{"title":{"text":""}}],"plotOptions":{"line":{"turboThreshold":0}},"credits":{"href":"","text":""},"chart":{"zoomType":"xy"},"title":{"text":""},"xAxis":[{"title":{"text":""}}]}
"""
In [7]:

display.html(
  <div>
    <script src="http://code.highcharts.com/stock/highstock.js"></script>
    <script src="http://code.highcharts.com/stock/modules/exporting.js"></script>
    <script src="http://www.highcharts.com/js/themes/grid.js"></script>
  </div>
​
)
In [8]:

$
val id = "graph"
display.html(<div id={id}>graph</div>)
val js = s"""
$$(function () {
    $$('#graph').highcharts(${hc.toJson})
    })
"""
display.js(js)
```

**Comment by cubefriendly** [comment]
True, it would be nice though to have some kind of integration.
I really like what I saw possible for Python. I hadn't have the time to really look at it but I still want to do something of the sort. I'll let you know when I get to it

**Comment by samthebest** [comment]
+1

This jupyter-scala is awesome, wisp is awesome. Combine and BOOM the world has changed for the better.

**Comment by chilang** [comment]
[Lightning](http://lightning-viz.org) works nicely for me -  [example](http://nbviewer.jupyter.org/urls/gist.githubusercontent.com/chilang/98326ad26192580e0630/raw/8f8888cbccc1d2e8348ec9f3d9e736c192be0fc0/Lightning%2520viz.ipynb). 

You'll need 
1. https://github.com/lightning-viz/lightning-scala
2. Run your own lightning server or use the http://public.lightning-viz.org

**Comment by alexarchambault** [comment]
@chilang That looks great!

It should be possible to write a small lib, depending on both lightning and the scala-api module of Jupyter Scala, to make plotting even more practical. One could add extension methods on lightning objects to plot directly a chart. These would just need getting implicit `Publish[Evidence]` and `Evidence` (see around https://github.com/alexarchambault/jupyter-scala/blob/master/api/src/main/scala/jupyter/api/API.scala#L60), then call the right methods on them to display some HTML. I'm about to document this more, taking into account the latest developments.

FWIW, I'm using custom libs that render JS graphs with Highcharts, and plot.ly recently, that I think I'll push too.

**Comment by chilang** [comment]
[Bokeh](http://bokeh.pydata.org/en/latest/) seems to work well too - [example](http://nbviewer.jupyter.org/urls/gist.githubusercontent.com/chilang/b28319c2955d76219001/raw/645d4df74186548752a43f93eec3880e4e0d27d1/Bokeh.ipynb), and doesn't require running any server.

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one. [plotly-scala](https://github.com/alexarchambault/plotly-scala/blob/master/README.md#from-almond) supports it, and [vegas](https://github.com/vegas-viz/Vegas) should work from it too.
