### ISSUE TITLE
Suppress output of statements

### ISSUE THREAD

**Issue by praveen-srinivasan** [jupyter-scala/jupyter-scala#27]
Hi,
Is there a way to suppress the output of statements? 
For example, could I suppress "x: Int = 1" below?

In [24]: val x = 1
            x: Int = 1

Thanks,
Praveen

**Comment by alexarchambault** [comment]
Not as is... What you can do though, is wrapping your values in a singleton, like:
```scala
In [2]: object Values {
   ...:   val x = 2
   ...: }
defined object Values
```
which won't output the particular values, only the wrapper name.

**Comment by mbesancon** [comment]
Hi, 
having the same problem here, even in blocks
```scala
{
    3+2
    "hi"
    4
}
```
returns 
``` scala
res21_0: Int = 5
res21_1: String = "hi"
res21_2: Int = 4
```

**Comment by animeshsrivastava24** [comment]
Please see whether these links works for you or not: 
https://forums.databricks.com/questions/3745/how-to-suppress-cell-output.html 
https://stackoverflow.com/questions/31841828/how-to-suppress-printing-of-variable-values-in-zeppelin

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one. It mostly wraps [Ammonite](http://ammonite.io/) now. Ask for help there if it's still a problem for you.

**Comment by queirozfcom** [comment]
Is this possible now with some kind of ammonite configuration? I couldn't find any
