### ISSUE TITLE
Adding a Jar

### ISSUE THREAD

**Issue by babak12** [jupyter-scala/jupyter-scala#28]
Is there any way to load jar in Jupyter-scala? I used :cp /something.jar to load local jar files into Scala REPL. How can I do it with jupiyer-scala? Thanks

**Comment by praveen-srinivasan** [comment]
load.jar("/home/foo/bar.jar")

**Comment by alexarchambault** [comment]
@praveen-srinivasan Thanks for answering that !

**Comment by babak12** [comment]
Thank you guys!

**Comment by Mageswaran1989** [comment]
I couldn't understand above solution. I have a sbt assembled "jar" file. How to include that in jupyter-scala ?

**Comment by animeshsrivastava24** [comment]
If you want to add a local jar to Jupyter Scala , follow the instructions :  
Create a jar file for your project work 

Find the path to the jar 

Go to Jupyter Scala cell and type all the instructions in a single cell or split them in different cells as per your convenience  

import ammonite., ammonite.ops. 

val path =  java.nio.file.FileSystems.getDefault().getPath("/home/animesh/Bureau/lastest_n2s3/out/artifacts/root_jar/root.jar")  // here inside the " " add your path, I have added mine for example

val x = ammonite.ops.Path(path)

interp.load.cp(x) 

It works for me, please check for yourself.

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one. It mostly wraps [Ammonite](http://ammonite.io/) now. Ask for help there if it's still a problem for you.
