### ISSUE TITLE
Running Apache Spark- java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by babak12** [jupyter-scala/jupyter-scala#29]
Hi, I am trying to run Apache Spark in the notebook as follow:

load.jar("/Users/babak/App/spark-1.3.1/assembly/target/scala-2.10/spark-assembly-1.3.1-hadoop2.4.0.jar")
import org.apache.spark.SparkContext
import org.apache.spark.SparkConf
val conf = new SparkConf().setMaster("spark://smaster:7077").setAppName("test_jupyter")
val sc = new SparkContext(conf)

After the running the last line I see the following error in terminal:

2015-10-06 13:01:57.877 java[52661:3205521] Unable to load realm info from SCDynamicStore
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "sparkDriver-akka.actor.default-dispatcher-3"

I should say I am able to use spark from spark-shell (spark-shell --master spark://smaster:7077). So there is no problem with the Spark Cluster.

**Comment by babak12** [comment]
Ok, I found the solution in the one of the issue posted before:
If I add the following line to the kernel.json it solve the memory issue:
"env" : {"JVM_OPT": "-Xmx3g -XX MaxPermSize=128m"}.
However, now I get new error:
when I do this
val k = sc.parallelize(1 to 9)
val l = k.collect

when I run the line with collect it freezes. When I look at the workers' log, I see such an error:
Exception in thread "main" java.lang.reflect.UndeclaredThrowableException

**Comment by alexarchambault** [comment]
That's the right way of increasing memory.

About spark, you should follow [this example](https://github.com/alexarchambault/jupyter-scala/blob/topic/spark-example/examples/libraries/Spark.ipynb). Directly creating a SparkContext like you did should not work, it requires some setup that the library ammonite-spark from the example does.

**Comment by DanqingZ** [comment]
@babak12  I ran into the same issue, but I am wondering where can I find the kernel.json?

I found there that https://github.com/hohonuuli/sparknotebook
SBT_OPTS=-Xmx2048m ipython notebook --profile "Scala 2.11"

But I do not know where to add the line. 

Thanks for the help!

**Comment by skattoor** [comment]
For (possibly my own) further reference, the `kernel.json` file was located in `.local/share/jupyter/kernels`.
(Running stock CentOS Linux release 7.4)

**Comment by alexarchambault** [comment]
The [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop), soon to be the default, delegates almost all its spark stuff to [ammonite-spark](https://github.com/alexarchambault/ammonite-spark). Ask there for help once the README of the develop branch gets updated.
