### ISSUE TITLE
how can i load predefined utilities and code?

### ISSUE THREAD

**Issue by ittayd** [jupyter-scala/jupyter-scala#32]
E.g. I want a file that loads ammonite-spark, creates the context, throws in some helper functions, maybe a plotting library.

**Comment by alexarchambault** [comment]
I'm planning to add something that would make it easier to have setup like these, maybe something to be used like
```scala
setup("plotting-lib", "spark")
setup.spark(master = "yarn-client")
```

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one.
