### ISSUE TITLE
Pass CLASSPATH variable through to scala interpreter

### ISSUE THREAD

**Issue by tonycpsu** [jupyter-scala/jupyter-scala#33]
The scala REPL can pull in JAR files from the CLASSPATH like so:

```
$ CLASSPATH=/foo/bar/baz.jar scala
```

However, trying the same with `jupyter-console` doesn't seem to work:

```
$  CLASSPATH=/foo/bar/baz.jar jupyter-console --kernel=scala211
```

I know about `load.jar("/foo/bar/baz.jar")`, but it's much easier to use the environment variable than to have to load each jar individually.

**Comment by alexarchambault** [comment]
It can't be done as is, the kernel somehow filters the classpath it is started with, in order not to expose all of its own dependencies. Having some kind of predef, like [Ammonite](http://lihaoyi.github.io/Ammonite/) does, would allow to solve the problem by putting `load.jar` lines in it.

**Comment by maclockard** [comment]
Is it possible to just use the Ammonite predef, or will there need to be a separate predef created to work with the kernel?

**Comment by espears4sq** [comment]
I have the same question as @maclockard . How do we define predef scripts that will be picked up when running both of `jupyter notebook` (and selecting the scala kernel), and `jupyter console --kernel scala`?

I tried modifying the ammonite predef in `~/.ammonite`, but the neither method of launching jupyter-scala will load or execute any files from that path at all. Is there a different location for the jupyter-based equivalent predef?

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one. It accepts a `--predef` option to run some code upfront.
