### ISSUE TITLE
Configure java.library.path

### ISSUE THREAD

**Issue by kmader** [jupyter-scala/jupyter-scala#36]
For using libraries with JNI it is important to be able to change `java.library.path`. This is possible by a very hacked approach (taken from http://fahdshariff.blogspot.be/2011/08/changing-java-library-path-at-runtime.html), but it would be better to have a command load.library which handled this

``` scala
val newPath = System.getProperty("java.library.path").split(":") ++ Array(jniPath)
System.setProperty("java.library.path",newPath.distinct.mkString(":"))
//set sys_paths to null so that java.library.path will be reevaluated next time it is needed
val sysPathsField = classOf[ClassLoader].getDeclaredField("sys_paths");
sysPathsField.setAccessible(true);
sysPathsField.set(null, null);
```

**Comment by alexarchambault** [comment]
@kmader Indeed, a helper method on `load` for that would be helpful. I'll have a look as soon as I give some more love to jupyter-scala (in a few weeks I hope).

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one. It mostly wraps [Ammonite](http://ammonite.io/) now. Propose the idea there if you'd like.
