### ISSUE TITLE
How does one add libraries to the classpath?

### ISSUE THREAD

**Issue by hohonuuli** [jupyter-scala/jupyter-scala#4]
How do I add libraries to the classpath so that I can use them with jupyter-scala.

For example, IScala has a magic _sbt_ command like `%libraryDependencies += "org.apache.spark" %% "spark-assembly" % "1.1.0"`. Is there something simliar with _jupyter-scala_

p.s. Thanks for working on this project. I think it's great!

**Comment by alexarchambault** [comment]
You're fast, I just pushed things this morning! the links in the README needs to be updated, have a look at the *directory* they point to, you should download the .tar.xz or .zip, **not** the .tar.gz.
Then it's like in Ammonite, you should call load.ivy("org" %% "name" % "version"). (Keep one % at first pos if not a scala dependency).
I'll add more explanations in the README later today or tomorrow.

**Comment by hohonuuli** [comment]
Thanks for the quick response and the pointers. I'll give it a spin later today.

**Comment by alexarchambault** [comment]
Example I had at hand:

![jupyter-scala 4](https://cloud.githubusercontent.com/assets/7063723/7657061/46676f36-fb2f-11e4-87d7-3c809c9f997b.PNG)

I'll close once I have written some doc.

**Comment by hohonuuli** [comment]
On a related note, do you have a method to add additional repositories? Thanks!

**Comment by alexarchambault** [comment]
Maven ones - but in maybe half an hour (once Travis had built and published new ammonite-shell and jupyter-scala packages):

![resolvers](https://cloud.githubusercontent.com/assets/7063723/7658325/800a3f7a-fb39-11e4-8236-5504fa1c0e39.png)

**Comment by alexarchambault** [comment]
Shouldn't be too hard to add the other kind of repo that SBT support (Ivy like repo, SSH?, ...)

**Comment by hohonuuli** [comment]
That's great. I think the maven ones will cover about 95% of use cases. Especially if you can point it at a local repo ... `~/.m2`

**Comment by alexarchambault** [comment]
Haven't tested, but `load.resolver("Maven local repo" at "file:/home/.../.m2/repository")` should be ok (SBT does it this way). I didn't end up using `~/.m2` too often with SBT (more `~/.ivy2/local`, which is enabled by default, along with Maven Central).

**Comment by alexarchambault** [comment]
The packages with that can now be downloaded (note that links on the README were updated).

**Comment by damienstanton** [comment]
I'm having an issue trying this with central repository libraries (specifically Spark).
```scala
load.resolver("DefaultMavenRepository" at "https://repo1.maven.org/maven2")
```
completes fine, but then when I try
```scala
load.ivy("org.apache.spark" % "spark-core_2.11" % "1.6.0")
```
I get a resolution error:
```

:: problems summary ::
:::: WARNINGS
	Unable to reparse com.github.alexarchambault.jupyter#jupyter-scala-api_2.11.6;0.2.0-SNAPSHOT from sonatype-snapshots, using Thu Dec 24 09:50:58 EST 2015

	Choosing sonatype-snapshots for com.github.alexarchambault.jupyter#jupyter-scala-api_2.11.6;0.2.0-SNAPSHOT

	Unable to reparse com.github.alexarchambault#ammonite-api_2.11.6;0.3.1-SNAPSHOT from sonatype-snapshots, using Wed Oct 21 05:43:36 EDT 2015

	Choosing sonatype-snapshots for com.github.alexarchambault#ammonite-api_2.11.6;0.3.1-SNAPSHOT

	Unable to reparse com.github.alexarchambault.jupyter#jupyter-api_2.11;0.2.0-SNAPSHOT from sonatype-snapshots, using Wed Oct 21 11:03:52 EDT 2015

	Choosing sonatype-snapshots for com.github.alexarchambault.jupyter#jupyter-api_2.11;0.2.0-SNAPSHOT

		module not found: org.apache.spark#spark-core_2.11_2.11;1.6.0

	==== local: tried

	  /Users/damien/.ivy2/local/org.apache.spark/spark-core_2.11_2.11/1.6.0/ivys/ivy.xml

	==== public: tried

	  https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11_2.11/1.6.0/spark-core_2.11_2.11-1.6.0.pom

	==== sonatype-snapshots: tried

	  https://oss.sonatype.org/content/repositories/snapshots/org/apache/spark/spark-core_2.11_2.11/1.6.0/spark-core_2.11_2.11-1.6.0.pom

	==== DefaultMavenRepository: tried

	  https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11_2.11/1.6.0/spark-core_2.11_2.11-1.6.0.pom

	==== DefaultMavenRepository: tried

	  https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11_2.11/1.6.0/spark-core_2.11_2.11-1.6.0.pom

	==== DefaultMavenRepository: tried

	  http://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11_2.11/1.6.0/spark-core_2.11_2.11-1.6.0.pom
```

**Comment by alexarchambault** [comment]
@damienstanton Are you sure you didn't enter something like
```scala
load.ivy("org.apache.spark" %% "spark-core_2.11" % "1.6.0")
```
(notice the first two `%` signs, instead of just one) before that? Resolution seems to look for a module with name `spark-core_2.11_2.11`, that the former would bring.

If that's the case, note that in the next version, an addition of modules that made the resolution fail will be ignored, and not kept around like here. It should be pushed any time soon.

**Comment by leomrocha** [comment]
LOAD command fails. Value load not found

Should I open a new ticket or should it be handled here?

Here the errors:
![errors](https://cloud.githubusercontent.com/assets/3646521/13402965/ff47d14a-df12-11e5-91ac-e6ce38f1736b.png)

**Comment by alexarchambault** [comment]
Yep, sorry, see the [upcoming README](https://github.com/alexarchambault/jupyter-scala/tree/e1e3db4b9f013a2d8b785001ae6a390897bd20fa). That's [`classpath.add`](https://github.com/alexarchambault/jupyter-scala/tree/e1e3db4b9f013a2d8b785001ae6a390897bd20fa#classpathadd).

**Comment by gmachine1** [comment]
I have an ivy repository where the xml file is 1.1.1.160701194647/ivys/ivy-1.1.1.160701194647.xml but the jar is 1.1.1.160701194647/jars/schema-1.1.1.160701194647.jar , where schema is the module name. I ran classpath.addRepository on the pattern "[organisation]/[module]/[revision]/[type]s/[type]-[revision].[ext]" and it finds the xml but when it tries to find the jar it applies the same pattern, even when I also include the "[organization]/[module]/[revision]/[type]s/[module]-[revision].[ext]") pattern for the jar. How can I work around this?

**Comment by QuantScientist** [comment]
HI :)
In my system, classpath.add has no affect:

classpath.add("com.github.melrief" %% "purecsv" % "0.0.1")
classpath.add("org.scalanlp" %% "breeze_2.10" % "0.12")

// packages org.scalanlp:breeze_2.10:0.12,

import math.{exp, log}

import breeze.benchmark.{MyRunner, BreezeBenchmark}
import breeze.linalg.{softmax, DenseVector}
import breeze.stats.distributions.Rand

Main.scala:29: not found: value breeze
 ; import math.{exp, log} ; import breeze.benchmark.{MyRunner, BreezeBenchmark} ; import breeze.linalg.{softmax, DenseVector} ; import breeze.stats.distributions.Rand ; object LogisticFunction

Is this the correct syntax? 
Thanks

**Comment by neil90** [comment]
When I try to add local directory via
classpath.addPath("/usr/local/spark/jars")

All I see thats added to my classpath.path() shows 
/usr/local/spark/jars

And not all the individual jars located in the directory.

Per the documentation this should be correct syntax to add local jar folders but this does not seem to work as I can't import any spark classes

**Comment by drkmd8** [comment]
If you have only one scala installed on your machine, than classpath.add should be working fine. If you happen to installed scala 2.12 as I did when installing jupyter scala, then you would prefer using scala 2.11 and you can try this first:
import $ivy.`com.github.alexarchambault.ammonium:interpreter-api_2.11.8:0.4.0`

and then import packages such as:
import $ivy.`org.apache.spark:spark-sql_2.11:2.1.1`

**Comment by javadba** [comment]
The `import $ivy` construct is working in scala but not scala-spark: what is the syntax for that kernel?

**Comment by alexarchambault** [comment]
Closing this. The upcoming version of the kernel (on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop) for now) just wraps Ammonite. See [the Ammonite doc](http://ammonite.io/#import$ivy) for that.
