### ISSUE TITLE
Availability in anaconda channels?

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [jupyter-scala/jupyter-scala#42]
Hi,

I couldn't find `jupyter-scala` via anaconda channels, but I thought I would ask just in case there are any plans to do so at some point. Thanks!

**Comment by alexarchambault** [comment]
Hi,

It's not distributed via anaconda channels for now, although that would be nice if it was. I don't know enough of conda to setup that myself right now (I'm more used to the Java way of distributing binaries!), any help for that would be greatly appreciated.

**Comment by alexarchambault** [comment]
Closing for now. Could be re-opened if I or anyone else feel like giving this a try.
