### ISSUE TITLE
Cool Demos with ugly messages from load command

### ISSUE THREAD

**Issue by kmader** [jupyter-scala/jupyter-scala#45]
I have translated a few cool demos from the Java ImgLib2 community in the [ImgLib2-Notebooks](https://github.com/4Quant/ImgLib2-Notebooks) repo like this interpolation [demo](https://github.com/4Quant/ImgLib2-Notebooks/blob/master/Zoom-Interpolate.ipynb). The load command ruins it. I have already set `load.verbose=false` but that didn't help. Any way to hide all those messages so the notebooks are readable?

**Comment by alexarchambault** [comment]
Two ways:
- You could manually edit the `.ipynb` files, and remove the annoying resolution output directly. `.ipynb` files are standard JSON, it's quite easy to find one's way around in them. Although admittedly, that's not a very elegant thing to do.
- alternatively, wait for the next version! It's being tested a bit privately currently - I don't want to push it in a hurry. It should be a matter of days before I start pushing things. The output is much less verbose thanks to [this other project](https://github.com/alexarchambault/coursier) I worked on.

**Comment by alexarchambault** [comment]
Closing, as the upcoming version is around the corner (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
