### ISSUE TITLE
multiuser support

### ISSUE THREAD

**Issue by slel** [jupyter-scala/jupyter-scala#46]
Please provide (and/or document) multi-user support.

This is a prerequisite for making a Scala Jupyter kernel available on SageMathCloud:
https://github.com/sagemathinc/smc/issues/395#issuecomment-174999844

**Comment by alexarchambault** [comment]
@slel You mean, ways to install the kernel globally (like in `/usr/local/share/jupyter`)? That definitely should be added yes.

I'll need that to have the kernel work fine with jupyterhub, I might add it soon...

**Comment by e9t** [comment]
+1

**Comment by alexarchambault** [comment]
Closing, as the upcoming version is around the corner (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)). It supports user or global installation (run its launcher with `--help` to list the available options).
