### ISSUE TITLE
magic support

### ISSUE THREAD

**Issue by antonkulaga** [jupyter-scala/jupyter-scala#47]
It would be nice to be able to have scala in one cell and python in another one, as some libs are avaliable only in python. I know that such thing is done with  % lsmagic but I cannot run it with scala kernel

**Comment by alexarchambault** [comment]
There's nothing in Jupyter Scala to manage a python kernel on the side... It would be hard to make both kernels communicate anyway. I don't know if that would bring much compared to having a Python kernel in one tab, and a Scala one in another.

A funny feature that could be added though, would be to interpret some cells with Jython say, with the Scala and Jython cells sharing class loaders (so sharing variables, libs, ...). Provided that Jython misses some important Python libs like numpy, that possibly limits a bit the interest of that for now, but some people might find that interesting...

**Comment by alexarchambault** [comment]
Also, about the special commands of Jupyter Scala, see https://github.com/alexarchambault/jupyter-scala/issues/44#issuecomment-173385480.

I'm in the midst of writing a more decent doc for it, it should be pushed in a few days.

**Comment by dabro** [comment]
See my comment in [#44](https://github.com/alexarchambault/jupyter-scala/issues/44#issuecomment-173385480)

**Comment by Mageswaran1989** [comment]
@alexarchambault  it would be good to have a python as a standalone kernel along side the scala kernel, that way we dont have to switch between the notebooks and use both kernels under the notebook even though there is no sharing between the kernels.
Eg use: For education purpose / Comparing the code or algorithms between Python and Scala/Java

**Comment by alexarchambault** [comment]
Closing for now. Could be re-opened if I or anyone else feel like giving this a try.

**Comment by mardukbp** [comment]
> It would be nice to be able to have scala in one cell and python in another one, as some libs are avaliable only in python. I know that such thing is done with % lsmagic but I cannot run it with scala kernel

BeakerX [implements magics](https://web.archive.org/web/20200214134801/https://nbviewer.jupyter.org/github/twosigma/beakerx/blob/master/doc/python/KernelMagics.ipynb) that allow executing Scala code within a Python kernel.

[Apache Zeppelin](http://zeppelin.apache.org/) is a notebook (not related to Jupyter) in which each cell can be executed by a different interpreter. It supports Scala and Python among many other languages.
