### ISSUE TITLE
import of packages with renaming fails between cells

### ISSUE THREAD

**Issue by anton-molyboha** [jupyter-scala/jupyter-scala#49]
The following code, each line in a separate cell:

``` scala
import java.{io => jio}
import jio.File;
new File("/tmp");
```

results in the errors:

```
    Main.scala:16: object jio is not a member of package java
    import java.jio.File
                ^
    Main.scala:45: object jio is not a member of package java
    import java.jio.File
                ^
    Main.scala;54: not found: type File
    new File("/tmp")
        ^
```

Looks like "jio" is interpreted as an alias for "java.jio" while it should be an alias for "java.io". Attaching a demo notebook...

[package_import_with_renaming_failure.ipynb.zip](https://github.com/alexarchambault/jupyter-scala/files/108811/package_import_with_renaming_failure.ipynb.zip)

P.S.: This issue may be more appropriate in the ammonite project, but I don't know how to test it or construct an illustrative example for pure ammonite.

**Comment by alexarchambault** [comment]
@anton-molyboha See [here](http://lihaoyi.github.io/Ammonite/#Ammonite-REPL) for how to download and run Ammonite.

The error also happens in Ammonite, so it should be fixed there first, I think. Just submitted https://github.com/lihaoyi/Ammonite/issues/334 for that.

**Comment by alexarchambault** [comment]
Closing, that seems to work fine with the upcoming version (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
