### ISSUE TITLE
Dockerfile for jupyter-scala

### ISSUE THREAD

**Issue by yeonghoey** [jupyter-scala/jupyter-scala#58]
I like this project.

I wrote `Dockerfile` for jupyter-scala based on the newest version(2.11.7).

Take a look.
You can do with it whatever you want.
(Fork, Link on your README, Copy the `Dockerfile` to this repo, Or just ignore)

https://github.com/dockoey/jupyter-scala
https://hub.docker.com/r/dockoey/jupyter-scala/

Thanks.

**Comment by alexarchambault** [comment]
@yeonghoey That looks nice! Is it something you plan to maintain? I'm fine with it living in a separate repository, that's less work for me! I would link it from the README here then.

Also, you know you can easily add the 2.10 kernel along with the 2.11 one, by downloading and running its launcher too.

**Comment by yeonghoey** [comment]
Thanks!
Actually I didn't think about plan for its maintenance,
But I want to keep it reusable. I'll keep up with your.
And I'll work for 2.10 kernel on this weekend.

Have a nice day!
