### ISSUE TITLE
Unexpected behaviour of some scala statements in notebook vs REPL

### ISSUE THREAD

**Issue by bushmanov** [jupyter-scala/jupyter-scala#59]
The following toy example successfully runs in standard REPL on Ubuntu machine (scala 2.11.7, Java 1.8.0_72):

```
@annotation.tailrec
def fives(st:Int, end:Int):Unit = {
    if (st <= end) {
    println(st)
    fives(st+5, end)
    }
}
```

However, when I run the same in jupyter notebook I'm getting an error message:

```
Main.scala:25: could not optimize @tailrec annotated method fives: it is neither private nor final so can be overridden
def fives(st:Int, end:Int):Unit = {
```

Is it normal and expected?

**EDIT**

One more strange result. The following runs in scala REPL (even in Ammonite REPL):

```
scala> def double(x:Int) = x*2
double: (x: Int)Int

scala> val myDouble: (Int) => Int=double
myDouble: Int => Int = <function1>

scala> myDouble(10)
res1: Int = 20
```

But when I try to run this snippet in notebook I get:

```
Main.scala:25: missing arguments for method double in class $user;
follow this method with `_' if you want to treat it as a partially applied function
double 
```

**Comment by alexarchambault** [comment]
That should be fixed internally in [ammonium](https://github.com/alexarchambault/ammonium). User functions should be annotated as `final` by default, so that your example would be fine.

As a temporary workaround, you can add the `final` yourself, like
```scala
@annotation.tailrec
final def fives(st:Int, end:Int):Unit = {
    if (st <= end) {
    println(st)
    fives(st+5, end)
    }
}
```

It works then. Sorry for the late answer.

**Comment by alexarchambault** [comment]
About the second point, yes, that's a bug.

**Comment by alexarchambault** [comment]
Closing, that seems to work fine with the upcoming version (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).

**Comment by NightMachinary** [comment]
I see most online tutorials only using `@tailrec`, not `@annotation.tailrec`. Why is that? Does `almond` not import sth standard?
