### ISSUE TITLE
"psp std demo" notebook example does not work

### ISSUE THREAD

**Issue by jkaura** [jupyter-scala/jupyter-scala#60]
Executing the first line in file **psp-std.ipynb** fails in Jupyter notebook:
`interpreter.init("-Yno-imports", "-Yno-predef")`

The error output is:
`Main.scala:24: value init is not a member of ammonite.api.Interpreter`

Obviously, it seems that `interpreter` object does not expose `init` method (anymore).

The environment into which _jupyter-scala_ was installed is **WinPython 3.5.1.2 64-bit** under Windows 10 Pro 64-bit.

**Comment by alexarchambault** [comment]
I'm on it, that should be fixed in [ammonium](https://github.com/alexarchambault/ammonium). That was lost in the recent big update.

**Comment by alexarchambault** [comment]
Closing, as the upcoming version is around the corner (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
