### ISSUE TITLE
Add jars via classpath

### ISSUE THREAD

**Issue by lawben** [jupyter-scala/jupyter-scala#61]
The new [README](https://github.com/alexarchambault/jupyter-scala/blob/topic/update-readme/README.md) does not state how to add local jars. In the current version `load.jar()` doesn't work anymore. Is it possible to load jars directly or do they need to be published to a local maven repo?

**Comment by alexarchambault** [comment]
Yep, sorry, it should land [here](https://github.com/alexarchambault/jupyter-scala/blob/e1e3db4b9f013a2d8b785001ae6a390897bd20fa/README.md#classpathaddpath). That's like
```scala
classpath.addPath("/path/to/file.jar")
```

**Comment by Atry** [comment]
It does not work now
```
cmd2.sc:1: not found: value classpath
val res2 = classpath.addPath("/path/to/file.jar")
           ^
```

**Comment by Atry** [comment]
`interp.load.cp` is available. However it is not able to add a JAR from http URL.

**Comment by Atry** [comment]
I created an sbt plug-in for exporting classpath for Ammonite and Jupyter Scala

https://github.com/ThoughtWorksInc/sbt-ammonite-classpath/

**Comment by Key2Love** [comment]
If someone used @animeshsrivastava24 code above and encountered compilation failed error below.
![image](https://user-images.githubusercontent.com/33833308/95225930-f234da80-082e-11eb-8407-4c02458d4e46.png)
just comment frist line ‘import ammonite., ammonite.ops.’
![image](https://user-images.githubusercontent.com/33833308/95226245-493aaf80-082f-11eb-8031-f62a67a20f10.png)
Then it should work

**Comment by animeshsrivastava24** [comment]
@Key2Love Can you explain how are you getting the value of x without importing the libraries?
Did you read your error code of twice import?

**Comment by Key2Love** [comment]
@animeshsrivastava24 I didn't import the libraries before, it seems that almond  imports these libraries automatically. I test this by restarting the kernel, the console still reported twice report error.
