### ISSUE TITLE
Typeclass to define how the output is displayed

### ISSUE THREAD

**Issue by andreaferretti** [jupyter-scala/jupyter-scala#62]
The [iScala kernel](https://github.com/mattpap/IScala) had a nice mechanism that allows to customize the output based on the type. Basically, if you want to be able to display a type `A`, you have to define an implicit instance `HTMLDisplay[A]` (with a low-priority default that does `_.toString`).

This way, one can define how to visualize images, Bokeh plots and so on, and everything is rendered accordingly.

I see that in jupyter-scala there are a few methods like `display.html` and so on. It is a little less convenient, since one always has to figure the correct method for rendering, instead on relying on the compiler to summon the right typeclass.

Does a mechanism like the above exist for jupyter-scala?

**Comment by denisrosset** [comment]
You could implement an additional method following the construction of `show[T]`, with an implicit `PPrint[T]`-like argument (defining your own trait).

I'm writing my own abstractions in one project, to have customizable output: LaTeX, SVG (for objects with a graphical representation), the Scala code reconstructing the object, Matlab code reproducing the same object, etc...

I hope to release [this part](https://github.com/denisrosset/alasc/blob/master/core/src/main/scala/net/alasc/print/Print.scala) as a separate library later, and have Jupyter integration.

**Comment by alexarchambault** [comment]
Closing for now. Could be re-opened if I or anyone else feel like giving this a try.
