### ISSUE TITLE
Connection with Spyder

### ISSUE THREAD

**Issue by alpcakno** [jupyter-scala/jupyter-scala#64]
Hi,

Just wondering if there is a way to plug the Jupyter Scala in Ipython 3.0 inside Spyder.
Especially, using Connect to an existing Kernel  (Connection file with JSON or remote kernel)

**Comment by alexarchambault** [comment]
I don't really know Spyder. It seems quite taylored for Python though, I'm not sure kernels for other languages would be usable from it. (Are they? What about e.g. Julia?)

**Comment by arita27** [comment]
Hello,

Spyder is an IDE integrating Ipython 3.0 inside (excellent quality, like matlab style).

The python code is evaluating through Ipython.


There is a communication process from
Ipython to others kernel.

Wondering if we launch Scala Jupyter in standalone mode, we can communicate with the kernel of Ipython.

My question:

1) How IPython is launched and communicated with the JVM ?

2) is there a background server ?

Thanks
Kevin








On 05 Apr 2016, at 16:57, Alexandre Archambault <notifications@github.com> wrote:

I don't really know Spyder. It seems quite taylored for Python though, I'm not sure kernels for other languages would be usable from it. (Are they? What about e.g. Julia?)

―

**Comment by alexarchambault** [comment]
Closing, as the upcoming version is around the corner (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
