### ISSUE TITLE
Scala Syntax Highlighting Error

### ISSUE THREAD

**Issue by EvanOman** [jupyter-scala/jupyter-scala#85]
Not 100% sure where to post this so maybe you guys will be able to help me out!

I have noticed that Python syntax highlighting is being used rather than Scala syntax highlighting whenever the notebook is being rendered outside of the Jupyter notebook interface.

This happens on [Github](https://github.com/EvanOman/GuessTheStateTrick/blob/master/Guess%20The%20State.ipynb) and with the [NB HTML Conversion](http://www.evanoman.com/GuessTheState.html).

Any ideas about where the issue might be?

**Comment by alexarchambault** [comment]
@EvanOman What makes you say that? One can find the scala code under some `hl-scala` class in both links you provide (accordingly, the syntax highlighting in your examples is... perfectible, though - but it seems to be colored as scala).

**Comment by EvanOman** [comment]
Well the biggest thing is the red boxes around single quotes:

![image](https://cloud.githubusercontent.com/assets/1807879/16060843/6cded642-324f-11e6-81a4-28bdbc4bc2c6.png)

I guess I had assumed that the error was because Python syntax was being used, though single quotes should be just fine in Python.

I did change the color of the boxes on the non-github version so they are less noticeable, but I would like them gone.

**Comment by alexarchambault** [comment]
Closing, that seems to work fine with the upcoming version (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
