### ISSUE TITLE
Using Scala in JupyterHub

### ISSUE THREAD

**Issue by sudipto84goswami** [jupyter-scala/jupyter-scala#86]
Hi All,

I am trying to use SCALA kernel in JupyterHub. I have installed the same per below. However the same is not reflecting when using in JupyterHub.

Available kernels:
  scala211    /root/.ipython/kernels/scala211
  ir          /app/sasdata/jupyter/anaconda3/share/jupyter/kernels/ir
  python3     /usr/local/share/jupyter/kernels/python3
  sas         /usr/local/share/jupyter/kernels/sas

Can you pls advice.

**Comment by alexarchambault** [comment]
You don't give many details... :-)

I used the kernel from jupyterhub during a few months, so it works with it one way or another. jupyterhub can be a pain to configure though..

**Comment by mjs2600** [comment]
Is the issue that the kernel is in root's home?

**Comment by alexarchambault** [comment]
Closing, as the upcoming version is around the corner (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
