### ISSUE TITLE
Repo credentials?

### ISSUE THREAD

**Issue by analytically** [jupyter-scala/jupyter-scala#87]
It'd be great if one could specify repository credentials.

**Comment by alexarchambault** [comment]
:+1: 

Support for credentials was added [very recently](https://github.com/alexarchambault/coursier/blob/master/notes/1.0.0-M12.markdown#changes) in coursier, that handles the dependencies. Support for it could be added here (along with other things related to dependencies, exclusions in particular).

**Comment by analytically** [comment]
Awesome!

**Comment by SmedbergM** [comment]
I may be missing where this is implemented; do the commits above provide some kind of functionality equivalent to sbt's
`credentials += Credentials("path" / "to" / ".credentials")`
?

**Comment by alexarchambault** [comment]
Closing, that seems to work fine with the upcoming version (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)), following the instructions at http://ammonite.io/ (look for "authentication").
