### ISSUE TITLE
Problem with Spark Dataframes

### ISSUE THREAD

**Issue by masmart14** [jupyter-scala/jupyter-scala#89]
I set up Spark in the notebook like this:

@transient val Spark = new ammonite.spark.Spark
import Spark.{ sparkConf, sc, sqlContext }
sc

I am unable to cast Dataframe columns from, for example, String to Int. 
I get the following error: 
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 17.0 failed 1 times, most recent failure: Lost task 0.0 in stage 17.0 (TID 17, localhost): java.util.concurrent.ExecutionException: java.lang.Exception: failed to compile: org.codehaus.commons.compiler.CompileException: File 'generated.java', Line 91, Column 45: Decimal

I know that the code itself is fine because it works when I run it from spark-shell.

If I set up Spark this way instead:
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
val conf = new SparkConf().setAppName("appname").setMaster("local")
val sc = new SparkContext(conf)

The problem goes away and I am able to cast dataframe columns as I would expect.
But when I set the notebook up this way I get weird "not serializable" errors.

Very confused, any help is appreciated.

**Comment by alexarchambault** [comment]
I ran into this one some time ago... but forgot how I circumvented it :-| Are you using a recent version of the kernel?

**Comment by masmart14** [comment]
I believe so

**Comment by alexarchambault** [comment]
Closing, as the upcoming version is around the corner (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
