### ISSUE TITLE
Out[...] label for result should appear like other jupyter kernel do

### ISSUE THREAD

**Issue by exoego** [jupyter-scala/jupyter-scala#92]
I am wondering why jupyter-scala,  unlike other jupyter kernel,  do not show **Out[...]** label for result cell.
![out](https://cloud.githubusercontent.com/assets/127635/16404093/b89a2eaa-3d36-11e6-9a4a-fb16ba2070b1.png)

This might be just a cosmetic issue, but I think it is great if Out[...] labels are shown, since users can easily spot the red labels and distinguish them from In[...] cell or other cells.

**Comment by alexarchambault** [comment]
Closing, that seems to work fine with the upcoming version (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
